# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 971e3e9dd3c683ab4bcfb5b00572414feaee9cd08ca4a9b33a6d4bad6435738141bf88a7b6b74446ee851f0cf6ae4f9c45f3f6e3ed223b4ba92c394e607fcae6

test:
  secret_key_base: dd28f8a1d2c2ea2edec81162cdae0e6649fabf12221c79a2da351ea837a0676c00b5b8bd2107047648871cd250b30df5602f682100a9457401d551fa1dbe3221

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
